### ISSUE TITLE
for blogspot

### ISSUE THREAD

**Issue by ashrafulazom** [developit/optimize-plugin#11]
how to use this code in google blogspot?

**Comment by marvinhagemeister** [comment]
This is a very broad question about programming in the general sense and out of scope to answer here.

Optimize-plugin is a plugin written for webpack. Webpack is most commonly used to prepare assets for single page applications written with web technologies. So to be able to use this plugin you need to have control over your build pipeline, use webpack and have access to the webpack configuration.
