### ISSUE TITLE
[Feature Request/Question] Non ECMAScript polyfills

### ISSUE THREAD

**Issue by DreierF** [developit/optimize-plugin#15]
Hi,

As far as I understand this plugin is only capable of providing polyfills for features that are supported by core-js.

Things like [classList](https://www.npmjs.com/package/eligrey-classlist.js), [fetch](https://www.npmjs.com/package/whatwg-fetch), [element-remove](https://www.npmjs.com/package/element-remove) or [FormData](https://www.npmjs.com/package/formdata-polyfill) are not available via core-js.

Is there already a way to make those polyfills available only in the ES5 version?

**Comment by developit** [comment]
@DreierF Yes - DOM polyfiling is far too difficult to implement via static analysis. My blanket recommendation is to import the polyfills you need manually, via [polyfill.io](https://github.com/Financial-Times/polyfill-service) or [dom4](https://github.com/WebReflection/dom4).
