### ISSUE TITLE
NPM version multiple majors behind source code

### ISSUE THREAD

**Issue by pjlee11** [developit/optimize-plugin#18]
Hey there 👋 

I could be wrong but it looks like [npm only has version 1.0.0](https://www.npmjs.com/package/optimize-plugin) and this project is now up to version 3.2.0 in github?

Just wondering if the published version difference might be why I'm seeing some issues on a super basic setup.

**Comment by developit** [comment]
@pjlee11 hiya - sorry about that, I haven't been able to dedicate enough time to this project. I do have a [full example application](https://realworld.preactjs.com) showing optimize-plugin + Preact, but I haven't open-sourced it yet for a number of unrelated reasons. 

I'm not sure why the package.json version ended up as 3.2.0 on GitHub, but FWIW it's the same version currently published to npm as 1.0.0. I'd been using this plugin for a year prior to release, and I think I just forgot to commit the version reset when I made the project public.
