### ISSUE TITLE
SyntaxError 'with' in strict mode

### ISSUE THREAD

**Issue by GoFzy** [developit/optimize-plugin#23]
@developit Hi, I removed the babel loader previously configured in webpack
![image](https://user-images.githubusercontent.com/46565627/149752985-fef8413d-ffe5-4ddd-ad64-277d09140d3a.png)
And added optimize-plugin to plugins
![image](https://user-images.githubusercontent.com/46565627/149753159-51f77ef4-bbd9-4057-aa5e-ff23d057ad4b.png)
The result shows 「No polyfills bundle was created」, and keeps reporting 「SyntaxError」 at the same time
![image](https://user-images.githubusercontent.com/46565627/149753684-50d88fc7-14c5-41a8-a4e6-9c542006579c.png)
Is there something wrong with my configuration?

**Comment by GoFzy** [comment]
webpack": "^4.39.1",
"optimize-plugin": "^1.1.0"

**Comment by developit** [comment]
Looks like this happened because the plugin was processing any file that ends with `"js"`. I've opened #24 to tighten that list, which should mean it no longer tries to process `.ejs` files.
